# .github/workflows/deploy.yml

name: Deploy ao GitHub Pages

on:
  push:
    branches:
      - main # O branch principal que você usa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use a versão mais recente que você tem

    - name: Instalar Dependências
      run: npm install

    - name: Construir Aplicativo (Build)
      run: npm run build

    - name: Configurar Caminho Base para Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # O DIRETÓRIO DE PUBLICACAO É A PASTA 'dist'
        publish_branch: gh-pages # Cria um novo branch só para o deploy